"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import {ChangeEvent,useEffect,useState} from "react";
import ImageAnnotator,{ImageNote,RenderMode} from "./image-annotator";
type Stage="setup"|"analysis"|"design"|"render";
const spaceTypes=["客廳","臥室","餐廳","書房","商業空間","其他"],styles=["日式","奶茶奢華","現代極簡","北歐","侘寂","自訂"];
export default function DesignerStudio(){
 const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[project,setProject]=useState("未命名提案"),[client,setClient]=useState(""),[spaceType,setSpaceType]=useState("客廳"),[style,setStyle]=useState("現代極簡"),[customStyle,setCustomStyle]=useState(""),[styleResearch,setStyleResearch]=useState(""),[imageNotes,setImageNotes]=useState<ImageNote[]>([]),[renderMode,setRenderMode]=useState<RenderMode>("strict"),[keep,setKeep]=useState(""),[remove,setRemove]=useState(""),[add,setAdd]=useState(""),[other,setOther]=useState(""),[analysis,setAnalysis]=useState(""),[design,setDesign]=useState(""),[result,setResult]=useState(""),[stage,setStage]=useState<Stage>("setup"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState("");
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 function choose(next:File|undefined){if(!next)return;if(!["image/jpeg","image/png","image/webp"].includes(next.type)||next.size>15*1024*1024)return setError("請選擇 15 MB 以下的 JPG、PNG 或 WEBP");if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next));setImageNotes([]);setError("")}
 async function formPost(url:string,fields:Record<string,string>,image:File|Blob){const body=new FormData(),normalized=await normalizeImage(image);body.append("image",normalized,"room.png");Object.entries(fields).forEach(([k,v])=>body.append(k,v));const response=await fetch(url,{method:"POST",body}),json=await response.json();if(!response.ok)throw new Error(json.error||"處理失敗");return json}
 async function analyze(){if(!file)return setError("請先上傳現場照片");if(style==="自訂"&&!customStyle.trim())return setError("請填寫自訂風格");setBusy(true);setError("");try{if(style==="自訂"){const response=await fetch("/api/research-style",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({style:customStyle})}),research=await response.json();if(!response.ok)throw new Error(research.error||"風格搜尋失敗");setStyleResearch(research.research)}const data=await formPost("/api/analyze-space",{annotations:noteSummary(imageNotes),modelLock:String(renderMode!=="redesign")},file);setAnalysis(data.analysis);setStage("analysis")}catch(e){setError(e instanceof Error?e.message:"分析失敗")}finally{setBusy(false)}}
 async function plan(){setBusy(true);setError("");try{const resolvedStyle=style==="自訂"?`${customStyle}\n\nGPT 搜尋整理的視覺參考：\n${styleResearch}`:style;const response=await fetch("/api/create-design",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysis:`空間類型：${spaceType}\n${analysis}`,style:resolvedStyle,keep,remove,add,other,modelLock:renderMode!=="redesign",annotations:noteSummary(imageNotes)})}),data=await response.json();if(!response.ok)throw new Error(data.error);setDesign(data.design);setStage("design")}catch(e){setError(e instanceof Error?e.message:"規劃失敗")}finally{setBusy(false)}}
 async function render(){if(!file)return;setBusy(true);setError("");try{const resolvedStyle=style==="自訂"?`${customStyle}\n\n${styleResearch}`:style;const data=await formPost("/api/render",{design,style:resolvedStyle,keep,remove,add,other,annotations:noteSummary(imageNotes),modelLock:String(renderMode!=="redesign"),renderMode},file);setResult(data.image);setStage("render")}catch(e){setError(e instanceof Error?e.message:"生成失敗")}finally{setBusy(false)}}
 async function revise(){if(!result||!revision.trim())return;setBusy(true);try{const blob=await(await fetch(result)).blob(),data=await formPost("/api/revise",{revision,design,annotations:noteSummary(imageNotes),modelLock:String(renderMode!=="redesign"),renderMode},blob);setResult(data.image);setRevision("")}catch(e){setError(e instanceof Error?e.message:"續改失敗")}finally{setBusy(false)}}
 function saveImage(){if(!result)return;const a=document.createElement("a");a.href=result;a.download=`${project}-提案.webp`;a.click()}
 const steps:[[Stage,string,string],[Stage,string,string],[Stage,string,string],[Stage,string,string]]=[["setup","01","專案設定"],["analysis","02","空間分析"],["design","03","設計策略"],["render","04","渲染與續改"]];
 return <main className="designer-shell"><header className="designer-top"><div className="designer-brand"><span>金</span><div><b>金鼎設計師工作台</b><small>AI DESIGNER CONSOLE</small></div></div><div className="project-name"><small>目前專案</small><input value={project} onChange={e=>setProject(e.target.value)}/></div><a href="/">客戶版預覽 ↗</a></header><div className="designer-layout"><aside className="designer-nav"><div className="designer-user"><i>JD</i><div><b>設計師模式</b><span>專業控制已開啟</span></div></div><nav>{steps.map(([key,no,label])=><button key={key} className={stage===key?"active":""} onClick={()=>setStage(key)} disabled={key!=="setup"&&!analysis}><span>{no}</span>{label}</button>)}</nav><div className="engine-note"><b>三層 AI 引擎</b><span>Space Analyzer</span><span>Design Director</span><span>Render Director</span></div></aside><section className="designer-main"><div className="designer-heading"><div><p>PROFESSIONAL WORKFLOW</p><h1>{stage==="setup"?"建立設計任務":stage==="analysis"?"檢視空間分析":stage==="design"?"編輯設計策略":"渲染成果與續改"}</h1></div><div className="stage-state"><i className={analysis?"done":""}/>分析 <i className={design?"done":""}/>規劃 <i className={result?"done":""}/>渲染</div></div>{error&&<p className="designer-error">{error}</p>}{stage==="setup"&&preview&&<ImageAnnotator image={preview} notes={imageNotes} onChange={setImageNotes} mode={renderMode} onModeChange={setRenderMode}/>} 
 {stage==="setup"&&<div className="setup-grid"><section className="designer-card"><h2>現場基礎資料</h2><label className="designer-upload">{preview?<img src={preview} alt="現場照片"/>:<div><b>＋ 上傳現場照片</b><span>JPG / PNG / WEBP · 15 MB 以下</span></div>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e:ChangeEvent<HTMLInputElement>)=>choose(e.target.files?.[0])}/></label><div className="designer-fields"><label>客戶／案件名稱<input value={client} onChange={e=>setClient(e.target.value)} placeholder="例：林宅客廳改造"/></label><label>空間類型<select value={spaceType} onChange={e=>setSpaceType(e.target.value)}>{spaceTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>主風格<select value={style} onChange={e=>{setStyle(e.target.value);setStyleResearch("")}}>{styles.map(x=><option key={x}>{x}</option>)}</select></label></div>{style==="自訂"&&<div className="designer-custom-style"><label>自訂風格<input value={customStyle} onChange={e=>{setCustomStyle(e.target.value);setStyleResearch("")}} placeholder="例如：歐美精品飯店、法式奶油復古、自然洞穴風"/></label><small>啟動分析時會先由 GPT 搜尋設計案例，整理材質、配色、家具與配置參考。</small>{styleResearch&&<p>✓ 風格參考研究已完成</p>}</div>}</section><section className="designer-card"><h2>設計限制與需求</h2><label>不可改動／必須保留<textarea value={keep} onChange={e=>setKeep(e.target.value)} placeholder="建築結構、門窗、設備、家具…"/></label><label>拆除或移除<textarea value={remove} onChange={e=>setRemove(e.target.value)} placeholder="舊家具、裝飾、雜物…"/></label><label>新增配置<textarea value={add} onChange={e=>setAdd(e.target.value)} placeholder="家具、收納、燈具、軟裝…"/></label><label>設計備註<textarea value={other} onChange={e=>setOther(e.target.value)} placeholder="家庭成員、生活習慣、材質偏好…"/></label><button className="designer-primary" disabled={!file||busy} onClick={analyze}>啟動 Space Analyzer →</button></section></div>}
 {stage==="analysis"&&<div className="review-layout"><section className="designer-card visual-card"><img src={preview} alt="分析中的空間"/><span>現場照片 · {spaceType}</span></section><section className="designer-card editor-card"><div className="card-head"><h2>AI 空間分析</h2><button onClick={analyze}>重新分析</button></div><p>可直接修正 AI 誤判，修正內容將成為下一階段依據。</p><textarea value={analysis} onChange={e=>setAnalysis(e.target.value)}/><button className="designer-primary" disabled={!analysis.trim()||busy} onClick={plan}>確認分析，建立設計策略 →</button></section></div>}
 {stage==="design"&&<div className="review-layout"><section className="designer-card brief-summary"><h2>專案摘要</h2><dl><dt>案件</dt><dd>{client||project}</dd><dt>空間</dt><dd>{spaceType}</dd><dt>風格</dt><dd>{style}</dd><dt>保留</dt><dd>{keep||"依現場結構"}</dd><dt>新增</dt><dd>{add||"依設計師策略"}</dd></dl></section><section className="designer-card editor-card"><div className="card-head"><h2>Design Director 策略</h2><button onClick={plan}>重新規劃</button></div><p>渲染前可編輯家具、材料、色彩、燈光與動線指令。</p><textarea value={design} onChange={e=>setDesign(e.target.value)}/><button className="designer-primary" disabled={!design.trim()||busy} onClick={render}>確認策略，產生高品質渲染 →</button></section></div>}
 {stage==="render"&&<div className="render-workbench"><section className="designer-card render-canvas">{result?<img src={result} alt="設計渲染成果"/>:<div className="empty-render">尚未產生渲染圖</div>}<div className="render-label">RENDER DIRECTOR · HIGH FIDELITY</div></section><aside className="designer-card render-control"><h2>渲染控制</h2><button className="designer-primary" disabled={!design||busy} onClick={render}>重新生成此方案</button><hr/><label>精準續改指令<textarea value={revision} onChange={e=>setRevision(e.target.value)} placeholder="只調整指定區域，其餘保持不變…"/></label><button className="designer-secondary" disabled={!revision.trim()||!result||busy} onClick={revise}>套用局部續改</button><button className="designer-download" disabled={!result} onClick={saveImage}>下載提案圖 ↓</button></aside></div>}</section></div>{busy&&<div className="designer-busy"><div>金</div><b>AI 正在處理專業設計任務</b><span>請保持此頁開啟</span></div>}</main>
}

async function normalizeImage(image:File|Blob):Promise<Blob>{try{const bitmap=await createImageBitmap(image),maxSide=2048,scale=Math.min(1,maxSide/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext("2d");if(!context)return image;context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return await new Promise<Blob>(resolve=>canvas.toBlob(blob=>resolve(blob||image),"image/png"))}catch{return image}}

function noteSummary(notes:ImageNote[]){return notes.length?notes.map((note,index)=>`${index+1}. 圖片水平 ${note.x}%、垂直 ${note.y}%：${note.text}`).join("\n"):"無定位備註"}
