"use client";
import {MouseEvent,useState} from "react";
export type ImageNote={x:number;y:number;x2?:number;y2?:number;text:string};
export type RenderMode="strict"|"annotated"|"redesign";
type Point={x:number;y:number};

export default function ImageAnnotator({image,notes,onChange,mode,onModeChange}:{image:string;notes:ImageNote[];onChange:(notes:ImageNote[])=>void;mode:RenderMode;onModeChange:(mode:RenderMode)=>void}){
 const[draft,setDraft]=useState(""),[tool,setTool]=useState<"point"|"line">("line"),[start,setStart]=useState<Point|null>(null);
 function point(event:MouseEvent<HTMLDivElement>):Point|null{const box=event.currentTarget.getBoundingClientRect(),img=event.currentTarget.querySelector("img");if(!img)return null;const scale=Math.min(box.width/img.naturalWidth,box.height/img.naturalHeight),width=img.naturalWidth*scale,height=img.naturalHeight*scale,left=box.left+(box.width-width)/2,top=box.top+(box.height-height)/2;if(event.clientX<left||event.clientX>left+width||event.clientY<top||event.clientY>top+height)return null;return{x:Math.round(((event.clientX-left)/width)*1000)/10,y:Math.round(((event.clientY-top)/height)*1000)/10}}
 function place(event:MouseEvent<HTMLDivElement>){if(!draft.trim())return;const p=point(event);if(!p)return;if(tool==="point"){onChange([...notes,{...p,text:draft.trim()}]);setDraft("");return}if(!start){setStart(p);return}onChange([...notes,{x:start.x,y:start.y,x2:p.x,y2:p.y,text:draft.trim()}]);setStart(null);setDraft("")}
 return <section className="image-annotator"><div className="annotation-heading"><b>模型保留與圖片定位</b><span>線型燈建議使用點到點標記</span></div><div className="render-mode"><button className={mode==="strict"?"active":""} onClick={()=>onModeChange("strict")}>只做材質光影</button><button className={mode==="annotated"?"active":""} onClick={()=>onModeChange("annotated")}>僅標記位置可改</button><button className={mode==="redesign"?"active":""} onClick={()=>onModeChange("redesign")}>允許重新設計</button></div><div className="annotation-tools"><button className={tool==="line"?"active":""} onClick={()=>{setTool("line");setStart(null)}}>↔ 點到點線段</button><button className={tool==="point"?"active":""} onClick={()=>{setTool("point");setStart(null)}}>● 單點標記</button></div><div className="annotation-entry"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="例如：沿此線段配置 3000K 暖白 LED 燈條"/><span>{!draft.trim()?"先輸入備註":tool==="line"?(start?"請點終點":"請點起點"):"請點位置"}</span></div><div className={`annotation-canvas ${draft.trim()?"is-placing":""}`} onClick={place}><img src={image} alt="定位備註用的空間圖片"/>{start&&<i className="pending" style={{left:`${start.x}%`,top:`${start.y}%`}}>起</i>}{notes.map((n,i)=>{const line=n.x2!==undefined&&n.y2!==undefined,dx=(n.x2??n.x)-n.x,dy=(n.y2??n.y)-n.y;return <span key={`${n.x}-${n.y}-${i}`}>{line&&<em style={{left:`${n.x}%`,top:`${n.y}%`,width:`${Math.hypot(dx,dy)}%`,transform:`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`}}/>}<i style={{left:`${n.x}%`,top:`${n.y}%`}}>{i+1}</i>{line&&<i className="endpoint" style={{left:`${n.x2}%`,top:`${n.y2}%`}}>{i+1}</i>}</span>})}</div>{notes.length>0&&<ol>{notes.map((n,i)=><li key={`${n.x}-${n.y}-${i}`}><b>{i+1}</b><span>{n.text}<small>{n.x2!==undefined?`線段：(${n.x}%, ${n.y}%) → (${n.x2}%, ${n.y2}%)`:`單點：(${n.x}%, ${n.y}%)`}</small></span><button onClick={()=>onChange(notes.filter((_,j)=>j!==i))}>刪除</button></li>)}</ol>}</section>
}
