"use client";
import {MouseEvent,PointerEvent,useState} from "react";
export type ImageNote={x:number;y:number;x2?:number;y2?:number;text:string};
export type RenderMode="strict"|"annotated"|"redesign";
type Point={x:number;y:number};
type Moving={index:number;pointer:Point;note:ImageNote};
const clamp=(n:number)=>Math.max(0,Math.min(100,n));

export default function ImageAnnotator({image,notes,onChange,mode,onModeChange}:{image:string;notes:ImageNote[];onChange:(notes:ImageNote[])=>void;mode:RenderMode;onModeChange:(mode:RenderMode)=>void}){
 const[draft,setDraft]=useState(""),[tool,setTool]=useState<"point"|"line">("line"),[start,setStart]=useState<Point|null>(null),[end,setEnd]=useState<Point|null>(null),[moving,setMoving]=useState<Moving|null>(null);
 function point(clientX:number,clientY:number,target:HTMLElement):Point|null{const box=(target.closest(".annotation-canvas")||target).getBoundingClientRect(),img=(target.closest(".annotation-canvas")||target).querySelector("img") as HTMLImageElement|null;if(!img)return null;const scale=Math.min(box.width/img.naturalWidth,box.height/img.naturalHeight),width=img.naturalWidth*scale,height=img.naturalHeight*scale,left=box.left+(box.width-width)/2,top=box.top+(box.height-height)/2;if(clientX<left||clientX>left+width||clientY<top||clientY>top+height)return null;return{x:Math.round(((clientX-left)/width)*1000)/10,y:Math.round(((clientY-top)/height)*1000)/10}}
 function placePoint(e:MouseEvent<HTMLDivElement>){if(tool!=="point"||!draft.trim())return;const p=point(e.clientX,e.clientY,e.currentTarget);if(p){onChange([...notes,{...p,text:draft.trim()}]);setDraft("")}}
 function begin(e:PointerEvent<HTMLDivElement>){if(tool!=="line"||!draft.trim()||moving)return;const p=point(e.clientX,e.clientY,e.currentTarget);if(p){e.currentTarget.setPointerCapture(e.pointerId);setStart(p);setEnd(p);e.preventDefault()}}
 function move(e:PointerEvent<HTMLDivElement>){if(start&&!moving){const p=point(e.clientX,e.clientY,e.currentTarget);if(p)setEnd(p)}}
 function finish(e:PointerEvent<HTMLDivElement>){if(!start||!end||moving)return;e.currentTarget.releasePointerCapture(e.pointerId);if(Math.hypot(end.x-start.x,end.y-start.y)>1){onChange([...notes,{x:start.x,y:start.y,x2:end.x,y2:end.y,text:draft.trim()}]);setDraft("")}setStart(null);setEnd(null)}
 function beginMove(index:number,e:PointerEvent<HTMLElement>){e.stopPropagation();const p=point(e.clientX,e.clientY,e.currentTarget);if(!p)return;e.currentTarget.setPointerCapture(e.pointerId);setMoving({index,pointer:p,note:{...notes[index]}})}
 function dragMove(e:PointerEvent<HTMLElement>){if(!moving)return;e.stopPropagation();const p=point(e.clientX,e.clientY,e.currentTarget);if(!p)return;const dx=p.x-moving.pointer.x,dy=p.y-moving.pointer.y,n=moving.note,next=[...notes];next[moving.index]={...n,x:clamp(n.x+dx),y:clamp(n.y+dy),x2:n.x2===undefined?undefined:clamp(n.x2+dx),y2:n.y2===undefined?undefined:clamp(n.y2+dy)};onChange(next)}
 function endMove(e:PointerEvent<HTMLElement>){if(!moving)return;e.stopPropagation();e.currentTarget.releasePointerCapture(e.pointerId);setMoving(null)}
 function copy(index:number){const n=notes[index],offset=3;onChange([...notes,{...n,x:clamp(n.x+offset),y:clamp(n.y+offset),x2:n.x2===undefined?undefined:clamp(n.x2+offset),y2:n.y2===undefined?undefined:clamp(n.y2+offset),text:`${n.text}（複製）`}])}
 return <section className="image-annotator"><div className="annotation-heading"><b>模型保留與圖片定位</b><span>已完成的標記可直接拖曳移動</span></div><div className="render-mode"><button className={mode==="strict"?"active":""} onClick={()=>onModeChange("strict")}>只做材質光影</button><button className={mode==="annotated"?"active":""} onClick={()=>onModeChange("annotated")}>僅標記位置可改</button><button className={mode==="redesign"?"active":""} onClick={()=>onModeChange("redesign")}>允許重新設計</button></div><div className="annotation-tools"><button className={tool==="line"?"active":""} onClick={()=>{setTool("line");setStart(null);setEnd(null)}}>↔ 拖曳線段</button><button className={tool==="point"?"active":""} onClick={()=>{setTool("point");setStart(null);setEnd(null)}}>● 單點標記</button></div><div className="annotation-entry"><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="例如：沿此線段配置 3000K 暖白 LED 燈條"/><span>{!draft.trim()?"先輸入備註":tool==="line"?(start?"拖曳中，放開完成":"在圖片按住並拖曳"):"請點位置"}</span></div><div className={`annotation-canvas ${draft.trim()?"is-placing":""}`} onClick={placePoint} onPointerDown={begin} onPointerMove={move} onPointerUp={finish}><img src={image} alt="定位備註用的空間圖片"/>{start&&end&&<span><em className="preview-line" style={lineStyle(start.x,start.y,end.x,end.y)}/><i className="pending" style={{left:`${start.x}%`,top:`${start.y}%`}}>起</i></span>}{notes.map((n,i)=>{const line=n.x2!==undefined&&n.y2!==undefined;return <span key={`${i}-${n.x}-${n.y}`}>{line&&<em className="movable-mark" style={lineStyle(n.x,n.y,n.x2!,n.y2!)} onPointerDown={e=>beginMove(i,e)} onPointerMove={dragMove} onPointerUp={endMove}/>}<i className="movable-mark" style={{left:`${n.x}%`,top:`${n.y}%`}} onPointerDown={e=>beginMove(i,e)} onPointerMove={dragMove} onPointerUp={endMove}>{i+1}</i>{line&&<i className="endpoint" style={{left:`${n.x2}%`,top:`${n.y2}%`}}>{i+1}</i>}</span>})}</div>{notes.length>0&&<ol>{notes.map((n,i)=><li key={`${n.x}-${n.y}-${i}`}><b>{i+1}</b><span>{n.text}<small>{n.x2!==undefined?`線段：(${n.x}%, ${n.y}%) → (${n.x2}%, ${n.y2}%)`:`單點：(${n.x}%, ${n.y}%)`}</small></span><button onClick={()=>copy(i)}>複製</button><button onClick={()=>onChange(notes.filter((_,j)=>j!==i))}>刪除</button></li>)}</ol>}</section>
}
function lineStyle(x:number,y:number,x2:number,y2:number){return{left:`${x}%`,top:`${y}%`,width:`${Math.hypot(x2-x,y2-y)}%`,transform:`rotate(${Math.atan2(y2-y,x2-x)*180/Math.PI}deg)`}}
